// Seed data — realistic architectural materials.
// Prices in AUD, unit costs are indicative.

const MATERIALS = [
  // ─────────── TIMBER ───────────
  { id: 'm-001', code: 'TBR·01', name: 'Victorian Ash', category: 'Timber',
    species: 'Eucalyptus regnans',
    supplier: 'Britton Timbers', origin: 'Tasmania, AU',
    finish: 'Clear matte lacquer', thickness: '19mm', dimensions: '2400×140',
    unitCost: 186, unit: 'm²', leadTime: '2–3 wk',
    swatch: { kind: 'woodgrain', tone: '#c9a778', grain: '#8a6236' },
    spec: 'Pale straw to pinkish-brown hardwood; straight-grained; mills cleanly. Janka 4.9kN. Suitable for interior joinery, veneer, lining boards. Source: FSC-certified coupe.',
    projects: ['p-brunswick', 'p-clifton'] },
  { id: 'm-002', code: 'TBR·02', name: 'Blackbutt', category: 'Timber',
    species: 'Eucalyptus pilularis',
    supplier: 'Australian Sustainable Hardwoods', origin: 'NSW, AU',
    finish: 'Oiled', thickness: '21mm', dimensions: '1800×130',
    unitCost: 214, unit: 'm²', leadTime: '3–4 wk',
    swatch: { kind: 'woodgrain', tone: '#b88a57', grain: '#6b451f' },
    spec: 'Golden yellow to pale brown. BAL-29 bushfire rating. Dense, durable. Common for flooring and external cladding.',
    projects: ['p-brunswick'] },
  { id: 'm-003', code: 'TBR·03', name: 'Western Red Cedar', category: 'Timber',
    species: 'Thuja plicata',
    supplier: 'Radial Timbers', origin: 'British Columbia, CA',
    finish: 'Cutek CD50 oil', thickness: '19mm', dimensions: '2400×86',
    unitCost: 168, unit: 'm²', leadTime: '4 wk',
    swatch: { kind: 'castellation', tone: '#a36948', grain: '#5a3319' },
    spec: 'Lightweight softwood, naturally decay-resistant. Warm amber tone weathering to silver. Specify for external screens, castellation, soffits.',
    projects: ['p-brunswick', 'p-clifton', 'p-hawthorn'] },
  { id: 'm-004', code: 'TBR·04', name: 'American White Oak', category: 'Timber',
    species: 'Quercus alba',
    supplier: 'Mathews Timber', origin: 'Appalachia, US',
    finish: 'Fumed & hard-waxed', thickness: '15mm engineered', dimensions: '2200×220',
    unitCost: 264, unit: 'm²', leadTime: '6 wk',
    swatch: { kind: 'woodgrain', tone: '#b4916a', grain: '#4d3620' },
    spec: 'Prime grade, rift & quartered. Stable for wide-plank flooring. Fuming (ammonia) deepens tannins to walnut-brown.',
    projects: ['p-hawthorn'] },
  { id: 'm-005', code: 'TBR·05', name: 'Spotted Gum', category: 'Timber',
    species: 'Corymbia maculata',
    supplier: 'Hazelwood & Hill', origin: 'QLD, AU',
    finish: 'Intergrain UltraDeck', thickness: '32mm', dimensions: '2000×90',
    unitCost: 232, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'woodgrain', tone: '#a97a4f', grain: '#5d3a1d' },
    spec: 'Decking-grade hardwood. Distinctive streaked appearance. Class 1 durability in-ground.',
    projects: [] },

  // ─────────── STONE ───────────
  { id: 'm-010', code: 'STN·01', name: 'Elba Bianco Marble', category: 'Stone',
    species: null,
    supplier: 'CDK Stone', origin: 'Carrara, IT',
    finish: 'Honed', thickness: '20mm slab', dimensions: '3100×1900',
    unitCost: 640, unit: 'm²', leadTime: '8–10 wk',
    swatch: { kind: 'marble', tone: '#ece6dc', vein: '#7a7468' },
    spec: 'White background with soft grey feathered veining. Recommended sealing with Akemi MN. Avoid acidic cleaners.',
    projects: ['p-hawthorn'] },
  { id: 'm-011', code: 'STN·02', name: 'Pietra Grey Limestone', category: 'Stone',
    species: null,
    supplier: 'Euro Marble', origin: 'Iran',
    finish: 'Brushed', thickness: '30mm', dimensions: '2800×1600',
    unitCost: 480, unit: 'm²', leadTime: '10 wk',
    swatch: { kind: 'marble', tone: '#5e5a55', vein: '#a8a49c' },
    spec: 'Deep charcoal with fine white veins. Dense limestone; suitable for vanities, feature walls. Brushed finish reduces fingerprint.',
    projects: ['p-clifton'] },
  { id: 'm-012', code: 'STN·03', name: 'Travertine Noce', category: 'Stone',
    species: null,
    supplier: 'Signorino', origin: 'Tivoli, IT',
    finish: 'Honed & filled', thickness: '20mm', dimensions: '2600×1500',
    unitCost: 395, unit: 'm²', leadTime: '9 wk',
    swatch: { kind: 'travertine', tone: '#9a7a5c', vein: '#624628' },
    spec: 'Walnut-brown travertine, vein-cut. Porous — factory-filled with matching resin. Interior use preferred.',
    projects: ['p-hawthorn'] },
  { id: 'm-013', code: 'STN·04', name: 'Bluestone — Sawn', category: 'Stone',
    species: null,
    supplier: 'Eco Outdoor', origin: 'VIC, AU',
    finish: 'Sawn', thickness: '30mm paver', dimensions: '600×400',
    unitCost: 172, unit: 'm²', leadTime: '2 wk',
    swatch: { kind: 'stone', tone: '#575a5a', grain: '#2f3131' },
    spec: 'Victorian basalt. Cool grey-blue. External paving, plinth, stair treads. Slip-rated P4.',
    projects: ['p-brunswick', 'p-clifton'] },

  // ─────────── COMPOSITE / BOARD ───────────
  { id: 'm-020', code: 'CMP·01', name: 'Laminex AbsoluteMatte — Ravine', category: 'Composite',
    species: null,
    supplier: 'Laminex', origin: 'AU',
    finish: 'Matte', thickness: '18mm MDF substrate', dimensions: '2400×1200',
    unitCost: 142, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'solid', tone: '#6b6158' },
    spec: 'Thermally fused melamine on E0 MDF. Anti-fingerprint. Warm taupe grey. Joinery shells, base fronts, sliders.',
    projects: ['p-brunswick', 'p-clifton', 'p-hawthorn'] },
  { id: 'm-021', code: 'CMP·02', name: 'Navurban Whittlesea Oak Veneer', category: 'Composite',
    species: null,
    supplier: 'Navurban (Laminex)', origin: 'AU',
    finish: 'Matte sealed', thickness: '18mm', dimensions: '2400×1200',
    unitCost: 218, unit: 'm²', leadTime: '2 wk',
    swatch: { kind: 'veneer', tone: '#b89268', grain: '#6d4a24' },
    spec: 'Reconstituted oak veneer on MDF. Consistent grain run. Cost-effective alternative to natural veneer.',
    projects: ['p-clifton'] },
  { id: 'm-022', code: 'CMP·03', name: 'VJ MDF Panelling — 100mm module', category: 'Composite',
    species: null,
    supplier: 'Custom joiner', origin: 'AU',
    finish: '2pac satin', thickness: '18mm', dimensions: '2400×1200',
    unitCost: 128, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'vj', tone: '#ede7da' },
    spec: 'Vertical-joint machined MDF, 100mm module. Primed & sprayed. Classic coastal / Federation detailing. Supplied primed — specify paint finish separately.',
    paintable: true, paintedWithId: 'm-050',
    projects: ['p-hawthorn'] },
  { id: 'm-023', code: 'CMP·04', name: 'Fluted MDF — 30mm half-round', category: 'Composite',
    species: null,
    supplier: 'Briggs Veneers', origin: 'AU',
    finish: 'Stained oak', thickness: '25mm', dimensions: '2400×1200',
    unitCost: 246, unit: 'm²', leadTime: '4 wk',
    swatch: { kind: 'fluted', tone: '#a67d52', grain: '#6b4a28' },
    spec: 'Machined fluting on MDF substrate, half-round profile. Reception joinery, feature walls. Specify stain reference.',
    paintable: true,
    projects: ['p-brunswick'] },

  // ─────────── METAL ───────────
  { id: 'm-030', code: 'MTL·01', name: 'Brushed Stainless Steel 316', category: 'Metal',
    species: null,
    supplier: 'Austral Wright Metals', origin: 'AU',
    finish: 'No.4 brushed', thickness: '1.5mm sheet', dimensions: '2400×1200',
    unitCost: 385, unit: 'm²', leadTime: '2 wk',
    swatch: { kind: 'brushed', tone: '#b8b5ae', grain: '#8a8780' },
    spec: 'Marine-grade. Kitchen splashbacks, benchtops, external fixings.',
    projects: ['p-hawthorn'] },
  { id: 'm-031', code: 'MTL·02', name: 'Blackened Brass Sheet', category: 'Metal',
    species: null,
    supplier: 'Surface Gallery', origin: 'AU',
    finish: 'Patinated, waxed', thickness: '2mm', dimensions: '1200×600',
    unitCost: 642, unit: 'm²', leadTime: '5 wk',
    swatch: { kind: 'solid', tone: '#3a2f22' },
    spec: 'Hand-patinated CZ108 brass. Each sheet unique. Joinery inlays, feature panels.',
    projects: [] },
  { id: 'm-032', code: 'MTL·03', name: 'Powdercoat — Dulux Namadji', category: 'Metal',
    species: null,
    supplier: 'Dulux Powders', origin: 'AU',
    finish: 'Matte', thickness: '80μm', dimensions: 'Applied to substrate',
    unitCost: 58, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'solid', tone: '#2a2826' },
    spec: 'Interior/exterior polyester powdercoat. Deep charcoal. Metal frames, handles.',
    projects: ['p-brunswick', 'p-clifton'] },
  { id: 'm-033', code: 'MTL·04', name: 'Copper Sheet — Natural', category: 'Metal',
    species: null,
    supplier: 'Craft Metals', origin: 'AU',
    finish: 'Mill', thickness: '0.7mm', dimensions: '2400×600',
    unitCost: 428, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'brushed', tone: '#b17149', grain: '#7a4525' },
    spec: 'Will patina unsealed to green-brown over 18–24 months exposed. Roofing, rainwater goods, feature cladding.',
    projects: [] },

  // ─────────── PAINT ───────────
  { id: 'm-050', code: 'PNT·01', name: 'Natural White', category: 'Paint',
    species: null,
    brand: 'Dulux', colourName: 'Natural White', colourCode: 'SW1F2',
    sheen: 'Low Sheen', system: 'Wash & Wear Interior', coats: 2,
    coveragePerL: 16, pricePerL: 92, substrates: 'Plasterboard, primed MDF',
    supplier: 'Dulux', origin: 'AU',
    finish: 'Low Sheen', thickness: '—', dimensions: '— applied coating',
    unitCost: 12, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'paint', tone: '#f0ece0', sheen: 'Low Sheen' },
    spec: 'Warm off-white. Dulux most-specified white. Anti-fingerprint acrylic. Low-VOC.',
    projects: ['p-hawthorn', 'p-brunswick'] },
  { id: 'm-051', code: 'PNT·02', name: 'Lexicon Quarter', category: 'Paint',
    species: null,
    brand: 'Dulux', colourName: 'Lexicon Quarter', colourCode: 'PG1H2',
    sheen: 'Matt', system: 'Wash & Wear Interior', coats: 2,
    coveragePerL: 16, pricePerL: 92, substrates: 'Plasterboard',
    supplier: 'Dulux', origin: 'AU',
    finish: 'Matt', thickness: '—', dimensions: '— applied coating',
    unitCost: 12, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'paint', tone: '#ecede8', sheen: 'Matt' },
    spec: 'Crisp cool white with blue undertone. Quarter strength. Trim & ceilings.',
    projects: ['p-clifton'] },
  { id: 'm-052', code: 'PNT·03', name: 'Milk', category: 'Paint',
    species: null,
    brand: 'Porter\'s Paints', colourName: 'Milk', colourCode: 'MILK',
    sheen: 'Dead Flat', system: 'Aqua Eggshell', coats: 2,
    coveragePerL: 12, pricePerL: 145, substrates: 'Plaster, primed timber',
    supplier: 'Porter\'s Paints', origin: 'AU',
    finish: 'Dead Flat', thickness: '—', dimensions: '— applied coating',
    unitCost: 22, unit: 'm²', leadTime: '2 wk',
    swatch: { kind: 'paint', tone: '#ece7d8', sheen: 'Dead Flat' },
    spec: 'Warm buttery off-white. Chalky matt reads soft in morning light.',
    projects: ['p-hawthorn'] },
  { id: 'm-053', code: 'PNT·04', name: 'Stone', category: 'Paint',
    species: null,
    brand: 'Porter\'s Paints', colourName: 'Stone', colourCode: 'STONE',
    sheen: 'Low Sheen', system: 'Aqua Low Sheen', coats: 2,
    coveragePerL: 12, pricePerL: 145, substrates: 'Plaster, primed MDF',
    supplier: 'Porter\'s Paints', origin: 'AU',
    finish: 'Low Sheen', thickness: '—', dimensions: '— applied coating',
    unitCost: 22, unit: 'm²', leadTime: '2 wk',
    swatch: { kind: 'paint', tone: '#b5ad9f', sheen: 'Low Sheen' },
    spec: 'Mid warm grey. Reads taupe against timber. Wet-area rated.',
    projects: [] },
  { id: 'm-054', code: 'PNT·05', name: 'Bondi', category: 'Paint',
    species: null,
    brand: 'Bauwerk', colourName: 'Bondi', colourCode: 'BONDI',
    sheen: 'Mineral Matt', system: 'Mineral Limewash', coats: 2,
    coveragePerL: 8, pricePerL: 220, substrates: 'Plaster, masonry',
    supplier: 'Bauwerk Colour', origin: 'AU',
    finish: 'Mineral Matt', thickness: '—', dimensions: '— applied coating',
    unitCost: 44, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'paint', tone: '#e6dcc4', sheen: 'Mineral Matt' },
    spec: 'Lime-based limewash. Soft chalk finish with subtle cloudy variation. Not wash-safe.',
    projects: ['p-fitzroy'] },
  { id: 'm-055', code: 'PNT·06', name: 'Roman', category: 'Paint',
    species: null,
    brand: 'Bauwerk', colourName: 'Roman', colourCode: 'ROMAN',
    sheen: 'Mineral Matt', system: 'Mineral Limewash', coats: 2,
    coveragePerL: 8, pricePerL: 220, substrates: 'Plaster, masonry',
    supplier: 'Bauwerk Colour', origin: 'AU',
    finish: 'Mineral Matt', thickness: '—', dimensions: '— applied coating',
    unitCost: 44, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'paint', tone: '#6e5544', sheen: 'Mineral Matt' },
    spec: 'Deep terracotta brown. Dramatic feature walls. Apply over Bauwerk basecoat.',
    projects: [] },
  { id: 'm-056', code: 'PNT·07', name: 'Seed', category: 'Paint',
    species: null,
    brand: 'Haymes', colourName: 'Seed', colourCode: 'H168W',
    sheen: 'Semi Gloss', system: 'Ultra Premium Interior', coats: 2,
    coveragePerL: 14, pricePerL: 115, substrates: 'Primed timber, MDF',
    supplier: 'Haymes Paint', origin: 'AU',
    finish: 'Semi Gloss', thickness: '—', dimensions: '— applied coating',
    unitCost: 16, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'paint', tone: '#cec4a9', sheen: 'Semi Gloss' },
    spec: 'Soft green-beige. Use on trim and joinery for subtle warmth.',
    projects: [] },
  { id: 'm-057', code: 'PNT·08', name: 'Black Caviar', category: 'Paint',
    species: null,
    brand: 'Haymes', colourName: 'Black Caviar', colourCode: 'H5BK',
    sheen: 'Matt', system: 'Ultra Premium Interior', coats: 2,
    coveragePerL: 14, pricePerL: 115, substrates: 'Plasterboard',
    supplier: 'Haymes Paint', origin: 'AU',
    finish: 'Matt', thickness: '—', dimensions: '— applied coating',
    unitCost: 16, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'paint', tone: '#1c1a18', sheen: 'Matt' },
    spec: 'Near-true black with hint of warm brown. Dramatic in low light.',
    projects: ['p-brunswick'] },
  { id: 'm-058', code: 'PNT·09', name: 'Alabaster', category: 'Paint',
    species: null,
    brand: 'Resene', colourName: 'Alabaster', colourCode: 'R60H',
    sheen: 'Low Sheen', system: 'SpaceCote Low Sheen', coats: 2,
    coveragePerL: 14, pricePerL: 105, substrates: 'Plasterboard, primed MDF',
    supplier: 'Resene', origin: 'NZ',
    finish: 'Low Sheen', thickness: '—', dimensions: '— applied coating',
    unitCost: 14, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'paint', tone: '#f4eee3', sheen: 'Low Sheen' },
    spec: 'Warm white with yellow undertone. Forgiving on north-facing rooms.',
    projects: [] },
  { id: 'm-059', code: 'PNT·10', name: 'Monument', category: 'Paint',
    species: null,
    brand: 'Taubmans', colourName: 'Monument', colourCode: 'T12.12.5',
    sheen: 'Matt', system: 'Endure Interior', coats: 2,
    coveragePerL: 14, pricePerL: 88, substrates: 'Plasterboard, primed timber',
    supplier: 'Taubmans', origin: 'AU',
    finish: 'Matt', thickness: '—', dimensions: '— applied coating',
    unitCost: 12, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'paint', tone: '#3c3d3d', sheen: 'Matt' },
    spec: 'Charcoal grey. Colorbond match. Ceilings in heritage interiors.',
    projects: [] },

  // ─────────── TEXTILE / SOFT ───────────
  { id: 'm-040', code: 'TXT·01', name: 'Kvadrat Remix 3 — 0933', category: 'Textile',
    species: null,
    supplier: 'Kvadrat Maharam', origin: 'DK',
    finish: 'Wool blend', thickness: '1.5mm', dimensions: '140cm roll',
    unitCost: 186, unit: 'l/m', leadTime: '4 wk',
    swatch: { kind: 'solid', tone: '#8a7560' },
    spec: '90% new wool / 10% nylon. 40,000 Martindale. EN1021 1&2. Upholstery, banquettes.',
    projects: ['p-clifton'] },
  { id: 'm-041', code: 'TXT·02', name: 'Armadillo Drift Weave — Oat', category: 'Textile',
    species: null,
    supplier: 'Armadillo', origin: 'IN / AU',
    finish: 'Hand-knotted', thickness: '12mm pile', dimensions: 'Made to size',
    unitCost: 920, unit: 'm²', leadTime: '12 wk',
    swatch: { kind: 'weave', tone: '#cfc2a6', grain: '#9a8c6c' },
    spec: 'GoodWeave-certified. Wool / jute. Custom sizing available.',
    projects: [] },

  // ─────────── APPLIANCE ───────────
  { id: 'm-100', code: 'APP·01', name: 'Pyrolytic Oven 600 — Graphite', category: 'Appliance',
    kind: 'appliance', subtype: 'oven', trade: 'Electrical',
    supplier: 'Miele', origin: 'DE', model: 'H7860 BP',
    finish: 'Graphite grey', dimensions: '595×595×570',
    unitCost: 6490, unit: 'ea', leadTime: '4 wk',
    swatch: { kind: 'solid', tone: '#3a3a3c' },
    spec: 'Single cavity pyrolytic oven. MasterChef Plus programmes. Concealed hinges. Hardwired 15A.',
    projects: ['p-hawthorn'] },
  { id: 'm-101', code: 'APP·02', name: 'Induction Cooktop 900', category: 'Appliance',
    kind: 'appliance', subtype: 'cooktop', trade: 'Electrical',
    supplier: 'Bora', origin: 'DE', model: 'PURU',
    finish: 'Black glass', dimensions: '830×515',
    unitCost: 11200, unit: 'ea', leadTime: '8 wk',
    swatch: { kind: 'solid', tone: '#151517' },
    spec: 'Integrated downdraft extraction. 4 zones, bridge function. Requires 32A dedicated circuit + exhaust duct.',
    projects: ['p-brunswick', 'p-hawthorn'] },
  { id: 'm-102', code: 'APP·03', name: 'Integrated Dishwasher 600', category: 'Appliance',
    kind: 'appliance', subtype: 'dishwasher', trade: 'Plumbing',
    supplier: 'Asko', origin: 'SE', model: 'DFI746U',
    finish: 'Panel-ready', dimensions: '598×820×570',
    unitCost: 2890, unit: 'ea', leadTime: '3 wk',
    swatch: { kind: 'solid', tone: '#c9c2b3' },
    spec: 'Fully integrated, custom door. 15 place settings. Requires 10A + cold water + 40mm waste.',
    projects: ['p-brunswick', 'p-clifton', 'p-hawthorn'] },
  { id: 'm-103', code: 'APP·04', name: 'Integrated Fridge/Freezer 760', category: 'Appliance',
    kind: 'appliance', subtype: 'fridge', trade: 'Joinery',
    supplier: 'Liebherr', origin: 'DE', model: 'ECBN 6256',
    finish: 'Panel-ready', dimensions: '762×2125×610',
    unitCost: 14900, unit: 'ea', leadTime: '12 wk',
    swatch: { kind: 'solid', tone: '#d4cec2' },
    spec: 'BioFresh + NoFrost. Fully integrated door panel. Plumbed ice/water. Specify hinge side in shop drawings.',
    projects: ['p-hawthorn'] },
  { id: 'm-104', code: 'APP·05', name: 'Concealed Rangehood 900', category: 'Appliance',
    kind: 'appliance', subtype: 'rangehood', trade: 'Electrical',
    supplier: 'Qasair', origin: 'AU', model: 'Grandeur 900',
    finish: 'Stainless', dimensions: '900×320×510',
    unitCost: 3420, unit: 'ea', leadTime: '4 wk',
    swatch: { kind: 'brushed', tone: '#b8b5ae', grain: '#8a8780' },
    spec: 'Undermount, concealed behind custom joinery. 1200m³/h. Ducted externally.',
    projects: ['p-brunswick', 'p-hawthorn'] },

  // ─────────── FITTING (tapware, sanitary) ───────────
  { id: 'm-110', code: 'FIT·01', name: 'Icon Mixer — Aged Brass', category: 'Fitting',
    kind: 'fitting', subtype: 'mixer', trade: 'Plumbing',
    supplier: 'Brodware', origin: 'AU', model: 'City Stik 1.8700',
    finish: 'Aged Brass', dimensions: '—',
    unitCost: 1480, unit: 'ea', leadTime: '6 wk',
    swatch: { kind: 'solid', tone: '#8a6b3a' },
    spec: 'Wall-mounted basin mixer. 180mm spout. WELS 5-star. Living finish — will patina naturally.',
    projects: ['p-hawthorn'] },
  { id: 'm-111', code: 'FIT·02', name: 'Sussex Scala Shower Set', category: 'Fitting',
    kind: 'fitting', subtype: 'shower', trade: 'Plumbing',
    supplier: 'Sussex', origin: 'AU', model: 'SC.04.CP',
    finish: 'Chrome', dimensions: '—',
    unitCost: 2260, unit: 'ea', leadTime: '3 wk',
    swatch: { kind: 'solid', tone: '#c7c9cb' },
    spec: 'Wall-mount rainhead + handshower diverter. Australian-made, lifetime warranty.',
    projects: ['p-clifton'] },
  { id: 'm-112', code: 'FIT·03', name: 'Above-counter Basin — Concrete', category: 'Fitting',
    kind: 'fitting', subtype: 'basin', trade: 'Plumbing',
    supplier: 'Concrete Nation', origin: 'AU',
    finish: 'Sealed concrete', dimensions: 'Ø400×120',
    unitCost: 890, unit: 'ea', leadTime: '5 wk',
    swatch: { kind: 'stone', tone: '#a49e93', grain: '#7a7569' },
    spec: 'Hand-cast GFRC. 40mm waste. Sealed for wet-area use. Colour variation expected.',
    projects: ['p-hawthorn'] },
  { id: 'm-113', code: 'FIT·04', name: 'Wall-hung Pan + Cistern', category: 'Fitting',
    kind: 'fitting', subtype: 'toilet', trade: 'Plumbing',
    supplier: 'Geberit', origin: 'CH', model: 'Sigma 8',
    finish: 'White', dimensions: '360×540',
    unitCost: 1740, unit: 'ea', leadTime: '2 wk',
    swatch: { kind: 'solid', tone: '#f5f2ed' },
    spec: 'In-wall cistern with Sigma 50 plate. Rimless pan. WELS 4-star.',
    projects: ['p-brunswick', 'p-clifton', 'p-hawthorn'] },
  { id: 'm-114', code: 'FIT·05', name: 'Freestanding Bath 1700', category: 'Fitting',
    kind: 'fitting', subtype: 'bath', trade: 'Plumbing',
    supplier: 'Apaiser', origin: 'AU', model: 'Haven',
    finish: 'Marble composite — Bone', dimensions: '1700×780×580',
    unitCost: 6890, unit: 'ea', leadTime: '10 wk',
    swatch: { kind: 'solid', tone: '#ece4d5' },
    spec: 'Marble & resin composite. Heat-retentive. Integrated overflow. Lifting crew required.',
    projects: ['p-hawthorn'] },

  // ─────────── LIGHT ───────────
  { id: 'm-120', code: 'LGT·01', name: 'Dot 40 Pendant — Aged Brass', category: 'Light',
    kind: 'light', subtype: 'pendant', trade: 'Electrical',
    supplier: 'Volker Haug', origin: 'AU', model: 'Dot 40',
    finish: 'Aged brass', dimensions: 'Ø400, 1.5m drop',
    unitCost: 2140, unit: 'ea', leadTime: '8 wk',
    swatch: { kind: 'solid', tone: '#b8955a' },
    spec: 'Spun brass pendant, E27. Dimmable with Leading-edge. Hand-finished — slight variation.',
    projects: ['p-hawthorn'] },
  { id: 'm-121', code: 'LGT·02', name: 'Trimless LED Downlight 75', category: 'Light',
    kind: 'light', subtype: 'downlight', trade: 'Electrical',
    supplier: 'Unios', origin: 'AU', model: 'Titan X 9W',
    finish: 'Matte white', dimensions: 'Ø92 cutout',
    unitCost: 215, unit: 'ea', leadTime: '1 wk',
    swatch: { kind: 'solid', tone: '#ecebe6' },
    spec: '9W LED, 2700K, 90CRI. Trimless plaster-in frame. Dimmable. IC-F rated.',
    projects: ['p-brunswick', 'p-clifton', 'p-hawthorn'] },
  { id: 'm-122', code: 'LGT·03', name: 'Bai Wall Sconce — Plaster', category: 'Light',
    kind: 'light', subtype: 'sconce', trade: 'Electrical',
    supplier: 'Apparatus', origin: 'US', model: 'Bai',
    finish: 'Lime plaster', dimensions: 'Ø300×110',
    unitCost: 3890, unit: 'ea', leadTime: '16 wk',
    swatch: { kind: 'solid', tone: '#eae3d2' },
    spec: 'Hand-applied lime plaster over metal. Integrated LED 2200K. Hardwired. Lead time reflects studio production.',
    projects: [] },
  { id: 'm-123', code: 'LGT·04', name: 'Linear Strip — 3000K', category: 'Light',
    kind: 'light', subtype: 'strip', trade: 'Electrical',
    supplier: 'Klik Systems', origin: 'AU', model: 'KStrip Pro',
    finish: 'Aluminium channel', dimensions: 'Per-metre',
    unitCost: 145, unit: 'm', leadTime: '2 wk',
    swatch: { kind: 'brushed', tone: '#c4c2bc' },
    spec: '24V, 14W/m, 2700K, 95CRI. Recessed aluminium channel + opal diffuser. Requires dimmable driver (spec separately).',
    projects: ['p-brunswick', 'p-hawthorn'] },

  // ─────────── JOINERY (hardware) ───────────
  { id: 'm-130', code: 'JNY·01', name: 'Mardeco M-Series Pull 192', category: 'Joinery',
    kind: 'joinery', subtype: 'handle', trade: 'Joinery',
    supplier: 'Mardeco', origin: 'AU', model: 'M5022.192',
    finish: 'Brushed brass', dimensions: '192mm CTC',
    unitCost: 84, unit: 'ea', leadTime: '1 wk',
    swatch: { kind: 'brushed', tone: '#b89762', grain: '#8a6e40' },
    spec: 'Solid brass cabinet pull. 192mm centres, 212mm overall. M4 threaded bolts included.',
    projects: ['p-brunswick', 'p-hawthorn'] },
  { id: 'm-131', code: 'JNY·02', name: 'Blum Legrabox Drawer Runner', category: 'Joinery',
    kind: 'joinery', subtype: 'runner', trade: 'Joinery',
    supplier: 'Blum', origin: 'AT', model: 'Legrabox Pure 550mm',
    finish: 'Orion grey', dimensions: '550×193',
    unitCost: 168, unit: 'pair', leadTime: '1 wk',
    swatch: { kind: 'solid', tone: '#6a6d70' },
    spec: '40kg rated. Tip-on Blumotion soft-close. Full extension. Specify drawer height M/K/C.',
    projects: ['p-brunswick', 'p-clifton', 'p-hawthorn'] },
  { id: 'm-132', code: 'JNY·03', name: 'Concealed Hinge — Blum Clip Top', category: 'Joinery',
    kind: 'joinery', subtype: 'hinge', trade: 'Joinery',
    supplier: 'Blum', origin: 'AT', model: '71B3550',
    finish: 'Nickel-plated', dimensions: '110° opening',
    unitCost: 12, unit: 'ea', leadTime: '1 wk',
    swatch: { kind: 'solid', tone: '#c8c5be' },
    spec: 'Clip-on mount, Blumotion integrated soft-close. 110° opening. Spec mounting plate separately.',
    projects: ['p-brunswick', 'p-clifton', 'p-hawthorn'] },

  // ─────────── FF&E: SEATING ───────────
  { id: 'm-200', code: 'FFE·01', name: 'Wishbone Chair CH24', category: 'FF&E',
    kind: 'ffe-seating', subtype: 'chair', trade: 'FF&E',
    supplier: 'Cult', origin: 'DK', model: 'Carl Hansen CH24',
    finish: 'Oiled oak, natural paper cord', dimensions: '550×520×760 (SH 450)',
    unitCost: 1680, unit: 'ea', leadTime: '10 wk',
    swatch: { kind: 'woodgrain', tone: '#c9a67a', grain: '#8a6236' },
    spec: 'Hans Wegner 1949. FSC-certified oak. 120 hand-tied paper cord weaves.',
    projects: ['p-hawthorn'] },
  { id: 'm-201', code: 'FFE·02', name: 'Mags Soft 2.5-seat Sofa', category: 'FF&E',
    kind: 'ffe-seating', subtype: 'sofa', trade: 'FF&E',
    supplier: 'Living Edge', origin: 'DK', model: 'HAY Mags Soft',
    finish: 'Vidar 3 / 0733 oatmeal', dimensions: '2280×1050×700',
    unitCost: 6840, unit: 'ea', leadTime: '14 wk',
    swatch: { kind: 'solid', tone: '#c9bfa6' },
    spec: 'Modular deep-seat sofa. Feather-wrapped foam. Fabric removable for cleaning.',
    projects: ['p-brunswick'] },
  { id: 'm-202', code: 'FFE·03', name: 'Shaker Counter Stool 650', category: 'FF&E',
    kind: 'ffe-seating', subtype: 'stool', trade: 'FF&E',
    supplier: 'Mr & Mrs White', origin: 'AU',
    finish: 'Blackened ash', dimensions: 'Ø380×650',
    unitCost: 890, unit: 'ea', leadTime: '6 wk',
    swatch: { kind: 'solid', tone: '#2a2622' },
    spec: 'Turned solid ash. Ebonised with water-based stain. Bench-made in Melbourne.',
    projects: ['p-brunswick', 'p-hawthorn'] },

  // ─────────── FF&E: TABLES ───────────
  { id: 'm-210', code: 'FFE·10', name: 'Plank Dining Table 2400', category: 'FF&E',
    kind: 'ffe-tables', subtype: 'dining', trade: 'FF&E',
    supplier: 'Fred International', origin: 'DK', model: 'Fredericia Plank',
    finish: 'Soaped oak', dimensions: '2400×1000×720',
    unitCost: 9420, unit: 'ea', leadTime: '16 wk',
    swatch: { kind: 'woodgrain', tone: '#d6c5a4', grain: '#997a4e' },
    spec: 'Solid FSC oak, trestle base. Soaped finish — periodic re-soaping required.',
    projects: ['p-hawthorn'] },
  { id: 'm-211', code: 'FFE·11', name: 'Tulou Coffee Table', category: 'FF&E',
    kind: 'ffe-tables', subtype: 'coffee', trade: 'FF&E',
    supplier: 'Cult', origin: 'DK', model: 'Cappellini Tulou',
    finish: 'Terracotta', dimensions: '700×420',
    unitCost: 2180, unit: 'ea', leadTime: '12 wk',
    swatch: { kind: 'solid', tone: '#a06446' },
    spec: 'Rotationally-moulded polyethylene. Indoor/outdoor. Lightweight.',
    projects: ['p-brunswick'] },

  // ─────────── FF&E: SOFT ───────────
  { id: 'm-220', code: 'FFE·20', name: 'Drift Weave Rug — 3×4m', category: 'FF&E',
    kind: 'ffe-soft', subtype: 'rug', trade: 'FF&E',
    supplier: 'Armadillo', origin: 'IN / AU', model: 'Drift Weave — Oat',
    finish: 'Hand-knotted wool/jute', dimensions: '3000×4000',
    unitCost: 11040, unit: 'ea', leadTime: '14 wk',
    swatch: { kind: 'weave', tone: '#cfc2a6', grain: '#9a8c6c' },
    spec: 'GoodWeave-certified. 12mm pile. Underlay recommended on hard floors.',
    projects: ['p-hawthorn'] },
  { id: 'm-221', code: 'FFE·21', name: 'Linen Curtain — Heavy Weight', category: 'FF&E',
    kind: 'ffe-soft', subtype: 'curtain', trade: 'FF&E',
    supplier: 'Mokum', origin: 'AU', model: 'Cascade — Fog',
    finish: 'S-fold, blockout lining', dimensions: 'Made to size',
    unitCost: 420, unit: 'm', leadTime: '6 wk',
    swatch: { kind: 'weave', tone: '#c5c3bc', grain: '#918f88' },
    spec: '100% Belgian linen, 320gsm. S-fold heading on concealed track. Specify drop + stack allowance.',
    projects: ['p-clifton', 'p-hawthorn'] },

  // ─────────── FF&E: LIGHTING (decorative, movable) ───────────
  { id: 'm-230', code: 'FFE·30', name: 'Flowerpot VP3 Table Lamp', category: 'FF&E',
    kind: 'ffe-lighting', subtype: 'table', trade: 'FF&E',
    supplier: 'Cult', origin: 'DK', model: '&Tradition VP3',
    finish: 'Matte red', dimensions: 'Ø230×360',
    unitCost: 640, unit: 'ea', leadTime: '4 wk',
    swatch: { kind: 'solid', tone: '#c34a3a' },
    spec: 'Verner Panton 1968 reissue. E14 LED. Plug-in — specify cable colour.',
    projects: ['p-brunswick'] },
  { id: 'm-231', code: 'FFE·31', name: 'Akari 10A Floor Lamp', category: 'FF&E',
    kind: 'ffe-lighting', subtype: 'floor', trade: 'FF&E',
    supplier: 'Anibou', origin: 'JP', model: 'Isamu Noguchi 10A',
    finish: 'Washi paper / bamboo', dimensions: 'Ø450×1600',
    unitCost: 1290, unit: 'ea', leadTime: '8 wk',
    swatch: { kind: 'solid', tone: '#ebe2c8' },
    spec: 'Handmade Gifu washi. Single E27 bulb. Packs flat for shipping.',
    projects: ['p-hawthorn'] },

  // ─────────── FF&E: ART / DECOR ───────────
  { id: 'm-240', code: 'FFE·40', name: 'Round Brass Mirror 900', category: 'FF&E',
    kind: 'ffe-art', subtype: 'mirror', trade: 'FF&E',
    supplier: 'Middle of Nowhere', origin: 'AU', model: 'Bjorn 900',
    finish: 'Antique brass frame', dimensions: 'Ø900×20',
    unitCost: 780, unit: 'ea', leadTime: '3 wk',
    swatch: { kind: 'solid', tone: '#a88654' },
    spec: 'Solid brass-plated frame. 4mm silver mirror. D-ring + French-cleat compatible.',
    projects: ['p-hawthorn'] },
  { id: 'm-241', code: 'FFE·41', name: 'Terracotta Vessel — Large', category: 'FF&E',
    kind: 'ffe-art', subtype: 'vessel', trade: 'FF&E',
    supplier: 'The DEA Store', origin: 'GR',
    finish: 'Unglazed terracotta', dimensions: 'Ø420×620',
    unitCost: 540, unit: 'ea', leadTime: '8 wk',
    swatch: { kind: 'solid', tone: '#b86f4a' },
    spec: 'Hand-thrown on Crete. Indoor use only — unsealed. Subtle variation per piece.',
    projects: [] },
];

const PROJECTS = [
  { id: 'p-brunswick', code: '23·14', name: 'Brunswick Residence',
    client: 'Ng / Park', stage: 'Construction', type: 'New build — single dwelling',
    location: 'Brunswick VIC', commenced: '2024-03', completion: '2026-08',
    budget: 'A$2.4M', lead: 'ED',
    description: 'Brick veneer replacement house on a mid-block 380m² lot. Two-storey, four-bedroom. Material palette centred on local hardwoods and recycled brick, with a restrained joinery package throughout.' },
  { id: 'p-clifton', code: '24·02', name: 'Clifton Hill Addition',
    client: 'Hassall', stage: 'Documentation', type: 'Rear addition + renovation',
    location: 'Clifton Hill VIC', commenced: '2024-09', completion: '2026-03',
    budget: 'A$1.1M', lead: 'LM',
    description: 'Two-room rear addition to a Victorian terrace. Cedar castellation screen to north, bluestone plinth, melamine-faced joinery with veneer feature shelving.' },
  { id: 'p-hawthorn', code: '23·07', name: 'Hawthorn East House',
    client: 'Fidalgo', stage: 'Handover', type: 'Full renovation',
    location: 'Hawthorn East VIC', commenced: '2023-06', completion: '2026-04',
    budget: 'A$3.8M', lead: 'ED',
    description: 'Heritage-listed Edwardian. Full interior refit with Elba Bianco marble kitchen, white oak flooring, painted VJ panelling to formal rooms.' },
  { id: 'p-fitzroy', code: '25·01', name: 'Fitzroy Studio',
    client: 'In-house', stage: 'Concept', type: 'Workplace / gallery',
    location: 'Fitzroy VIC', commenced: '2025-11', completion: '2026-12',
    budget: 'A$640K', lead: 'TH',
    description: 'Ground-floor warehouse fitout for practice studio + monthly gallery hang. Palette TBC.' },
];

const CATEGORIES = ['Timber', 'Stone', 'Composite', 'Metal', 'Paint', 'Textile',
  'Appliance', 'Fitting', 'Light', 'Joinery', 'FF&E'];

const PAINT_BRANDS = ['Dulux', 'Porter\'s Paints', 'Bauwerk', 'Haymes', 'Resene', 'Taubmans', 'Wattyl'];
const PAINT_SHEENS = ['Dead Flat', 'Matt', 'Mineral Matt', 'Low Sheen', 'Eggshell', 'Satin', 'Semi Gloss', 'Gloss'];

const LIBRARIES = [
  { id: 'lib-finishes',   name: 'Finishes',         description: 'Timber, stone, composite, metal, paint, textile — surfaces you specify by m².' },
  { id: 'lib-appliances', name: 'Appliances',       description: 'Ovens, cooktops, dishwashers, fridges, rangehoods.' },
  { id: 'lib-fittings',   name: 'Fittings',         description: 'Tapware, basins, sinks, toilets, baths, showers.' },
  { id: 'lib-lighting',   name: 'Lighting',         description: 'Hard-wired architectural lighting — pendants, downlights, sconces, strip.' },
  { id: 'lib-joinery',    name: 'Joinery hardware', description: 'Handles, pulls, hinges, runners, latches.' },
  { id: 'lib-ffe',        name: 'FF&E',             description: 'Furniture, fixtures, equipment — seating, tables, soft, decorative.' },
  { id: 'lib-bne-2026',   name: 'Brisbane 2026 Rates',
    description: 'Live supplier pricing — AUD ex-GST, April 2026. Pulled from Bord, Lighting Superstore, Marques Flooring, Bunnings, Plyco. Treat as ballpark — confirm with quotes.' },
];

// Items belonging to the Brisbane 2026 pricing library. Prices pulled from
// live supplier pages April 2026 — AUD ex-GST unless noted. See item.spec
// for source URLs + caveats.
const BNE_2026 = [
  { id: 'm-bne-01', code: 'MDF·VJ6', name: '6mm MDF — VJ grooved', category: 'Composite',
    kind: 'material',
    supplier: 'Plyco / Brisbane Building Materials', origin: 'AU',
    finish: 'Primed — paint separately', thickness: '6mm', dimensions: '2400×1200',
    unitCost: 40, unit: 'm²', leadTime: '2 wk',
    swatch: { kind: 'vj', tone: '#ede7da' },
    paintable: true,
    spec: 'Vertical-joint machined MDF, 6mm. Plain 6mm MDF is ~$18–20/m² at Bunnings; grooved profiles (Plyco Designer Groove VJ100/VJ150, Brisbane Building Materials) sit higher. Budget $30–50/m² supply-only; rate depends on groove module. Confirm with Plyco or BBM for Brisbane pickup.',
    projects: [] },

  { id: 'm-bne-02', code: 'PNT·DLX', name: 'Dulux Wash & Wear — 2 coats', category: 'Paint',
    kind: 'material',
    brand: 'Dulux', colourName: 'Natural White', colourCode: 'SW1F2',
    sheen: 'Low Sheen', system: 'Wash & Wear Interior', coats: 2,
    coveragePerL: 12, pricePerL: 8, substrates: 'Plasterboard, primed MDF',
    supplier: 'Dulux', origin: 'AU',
    finish: 'Low Sheen', thickness: '—', dimensions: '— applied coating',
    unitCost: 1.6, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'paint', tone: '#f0ece0', sheen: 'Low Sheen' },
    spec: 'Dulux ~$6–10/L across product lines (Wash & Wear, Aquanamel). Coverage ~10–16 m²/L on smooth surfaces — call it 12 m²/L. Material cost $0.60–$1.00/m² per coat → ~$1.20–$2/m² at 2 coats. Excludes labour.',
    projects: [] },

  { id: 'm-bne-10', code: 'VEN·SPG', name: 'Spotted Gum Veneer on 18mm MDF', category: 'Composite',
    kind: 'material',
    supplier: 'Bord Products', origin: 'AU',
    finish: 'Crown cut, 2.4mm veneer', thickness: '18mm', dimensions: '2400×1200',
    unitCost: 76, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'veneer', tone: '#a97a4f', grain: '#5d3a1d' },
    spec: 'Bord "from" price $219.45/sheet (2.88m²) → ~$76/m². Crown cut, 2.4mm veneer on standard 18mm MDF. Quarter-cut or MR substrate +10–15%. Trade accounts up to 10% off. Source: bord.com.au/products/spotted-gum-veneer-crown-cut-mdf',
    projects: [] },
  { id: 'm-bne-11', code: 'VEN·BLB', name: 'Blackbutt Veneer on 18mm MDF', category: 'Composite',
    kind: 'material',
    supplier: 'Bord Products', origin: 'AU',
    finish: 'Crown cut, 2.4mm veneer', thickness: '18mm', dimensions: '2400×1200',
    unitCost: 75, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'veneer', tone: '#b88a57', grain: '#6b451f' },
    spec: 'Bord "from" price $214.62/sheet (2.88m²) → ~$75/m². Crown cut, 2.4mm veneer on 18mm MDF. Source: bord.com.au/products/blackbutt-veneer-crown-cut-mdf',
    projects: [] },
  { id: 'm-bne-12', code: 'VEN·WAL', name: 'American Walnut Veneer on 18mm MDF', category: 'Composite',
    kind: 'material',
    supplier: 'Bord Products', origin: 'AU',
    finish: 'Crown cut, 2.4mm veneer', thickness: '18mm', dimensions: '2400×1200',
    unitCost: 65, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'veneer', tone: '#6b4a30', grain: '#3a2816' },
    spec: 'Bord "from" price $188.60/sheet (2.88m²) → ~$65/m². Crown cut, 2.4mm veneer on 18mm MDF. Source: bord.com.au/products/american-walnut-veneer-crown-cut-mdf',
    projects: [] },
  { id: 'm-bne-13', code: 'VEN·OAK', name: 'American Oak Veneer on 18mm MDF', category: 'Composite',
    kind: 'material',
    supplier: 'Bord Products', origin: 'AU',
    finish: 'Crown cut, 2.4mm veneer', thickness: '18mm', dimensions: '2400×1200',
    unitCost: 52, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'veneer', tone: '#b89268', grain: '#6d4a24' },
    spec: 'Bord "from" price $149.90/sheet (2.88m²) → ~$52/m². Crown cut, 2.4mm veneer on 18mm MDF. The cheapest of the Bord species range. Source: bord.com.au/products/american-oak-veneer-crown-cut-mdf',
    projects: [] },

  { id: 'm-bne-20', code: 'TBR·CSTL', name: 'WRC Castellation Cladding', category: 'Timber',
    kind: 'material',
    species: 'Thuja plicata',
    supplier: 'Modinex / cedar supplier', origin: 'AU / CA',
    finish: 'Raw — oil separately', thickness: '—', dimensions: '—',
    unitCost: 120, unit: 'm²', leadTime: '4 wk',
    swatch: { kind: 'castellation', tone: '#a36948', grain: '#5a3319' },
    spec: 'Western Red Cedar castellation supply-only ~$90–$160/m²; composite alternatives (Modinex, NewTechWood) ~$70–$130/m². Installed budget +$40–80/m² labour. Using $120/m² mid-point for real WRC.',
    projects: [] },

  { id: 'm-bne-21', code: 'TBR·SPG42', name: 'Spotted Gum 42×19 DAR — 1st Grade KD', category: 'Timber',
    kind: 'material',
    species: 'Corymbia maculata',
    supplier: 'Chippy\'s Outdoor', origin: 'QLD, AU',
    finish: 'DAR — raw', thickness: '19mm', dimensions: '42×19 — 1.8–3.0m lengths',
    unitCost: 5.6, unit: 'lm', leadTime: '2 wk',
    swatch: { kind: 'woodgrain', tone: '#a97a4f', grain: '#5d3a1d' },
    spec: '1st Grade, kiln-dried. ~$5.30/lm for set lengths 1.8–2.4m; ~$5.85/lm for longer 2.7–3.0m lengths. Using $5.60/lm mid-point. Ships nationally from Chippy\'s Outdoor.',
    projects: [] },
  { id: 'm-bne-22', code: 'TBR·BLB42', name: 'Blackbutt 42×19 DAR — Std & Better', category: 'Timber',
    kind: 'material',
    species: 'Eucalyptus pilularis',
    supplier: 'Warringah Timbers', origin: 'NSW, AU',
    finish: 'DAR — air-dried, raw', thickness: '19mm', dimensions: '42×19',
    unitCost: 7.32, unit: 'lm', leadTime: '2 wk',
    swatch: { kind: 'woodgrain', tone: '#b88a57', grain: '#6b451f' },
    spec: 'Standard & Better grade, air-dried. $7.32/lm confirmed at Warringah Timbers. Higher rate than kiln-dried Spotted Gum reflects Blackbutt species premium.',
    projects: [] },
  { id: 'm-bne-23', code: 'TBR·PIN42', name: 'Pine 42×19 DAR', category: 'Timber',
    kind: 'material',
    species: 'Pinus radiata',
    supplier: 'Bunnings', origin: 'AU / NZ',
    finish: 'DAR — raw', thickness: '19mm', dimensions: '42×19',
    unitCost: 4.5, unit: 'lm', leadTime: '1 wk',
    swatch: { kind: 'woodgrain', tone: '#e8d4a8', grain: '#b08a52' },
    spec: 'Standard grade ~$4.18–$4.20/lm; Premium grade ~$4.49–$4.81/lm. Using $4.50/lm mid-point. Most accessible Brisbane source — Bunnings stock.',
    projects: [] },

  { id: 'm-bne-30', code: 'FIN·WAX', name: 'Whittle Wax Evolution Matte', category: 'Paint',
    kind: 'material',
    brand: 'Whittle Waxes', colourName: 'Evolution Hardwax Oil — Matte', colourCode: 'EV-MATTE',
    sheen: 'Matt', system: 'Hardwax Oil', coats: 2,
    coveragePerL: 25, pricePerL: 103.5, substrates: 'Timber flooring, joinery',
    supplier: 'Marques Flooring Brisbane', origin: 'DE',
    finish: 'Matte', thickness: '—', dimensions: '— applied coating',
    unitCost: 4.15, unit: 'm²', leadTime: '1 wk',
    swatch: { kind: 'paint', tone: '#d6c8ad', sheen: 'Matt' },
    spec: '2L tin $207 confirmed (Marques Flooring Brisbane/Gold Coast). Coverage 40–60m² per 2L → $3.50–$5.20/m². Mid rate ~$4.15/m², material only. Source: marquesflooring.com.au/product/whittle-waxes-evolution-hardwax-oil-matte-2l/',
    projects: [] },

  { id: 'm-bne-40', code: 'LGT·LED27', name: 'LED Strip 2700K + Channel', category: 'Light',
    kind: 'light', subtype: 'strip', trade: 'Electrical',
    supplier: 'Lighting Superstore', origin: 'AU', model: '9.6W/m IP20 24V',
    finish: 'Aluminium channel + opal diffuser', dimensions: 'Per-metre',
    unitCost: 49, unit: 'm', leadTime: '2 wk',
    swatch: { kind: 'brushed', tone: '#c4c2bc' },
    spec: '2700K, 9.6W/m, IP20, 24V — $33/m confirmed (Lighting Superstore). Lower-spec 4.8–6W/m ~$15–20/m. Low-profile aluminium channel + diffuser $10–20/m. Combined budget $43–55/m at decent spec — using $49/m. Source: lightingsuperstore.com.au/products/led-strip-light-9-6w-2700k-per-metre-ip20-24v',
    projects: [] },

  { id: 'm-bne-50', code: 'BLD·BO', name: 'Blockout Roller Blind — S&I', category: 'FF&E',
    kind: 'ffe-soft', subtype: 'blind', trade: 'FFE',
    supplier: 'Blind supplier (TBC)', origin: 'AU',
    finish: 'Blockout fabric, standard cassette', dimensions: 'Made to size',
    unitCost: 85, unit: 'm²', leadTime: '3 wk',
    swatch: { kind: 'weave', tone: '#d9d4c7', grain: '#9c9689' },
    spec: 'Standard roller blockout $70–$100/m² supply & install. Premium / motorised $120–$200/m². Using $85/m² for standard. Source: floorvenue.com.au/how-much-do-blinds-cost/',
    projects: [] },

  { id: 'm-bne-60', code: 'JNY·SLD', name: 'Sliding Mechanism — 2 panel set', category: 'Joinery',
    kind: 'joinery', subtype: 'runner', trade: 'Joinery',
    supplier: 'Häfele / Hettich', origin: 'DE',
    finish: 'Top-hung bypass hardware', dimensions: 'Fits 2× panels ~0.6m² each',
    unitCost: 450, unit: 'set', leadTime: '2 wk',
    swatch: { kind: 'solid', tone: '#8a8780' },
    spec: 'Highly variable by system type. Basic top-hung bypass kit (Häfele, Hettich) $300–$600 for 2-panel set. Mid-spec architectural $800–$1,500. For small decorative panels (0.6m² each) the lower end is sufficient — using $450 mid-point.',
    projects: [] },

  { id: 'm-bne-70', code: 'VEN·EDG', name: 'Veneer Edge Tape — 50m roll', category: 'Composite',
    kind: 'material',
    supplier: 'Bord Products', origin: 'AU',
    finish: 'Matching species (Oak / Blackbutt / Spotted Gum / Walnut)', thickness: '0.4mm', dimensions: '50m roll',
    unitCost: 2, unit: 'm', leadTime: '2 wk',
    swatch: { kind: 'veneer', tone: '#b89268', grain: '#6d4a24' },
    spec: 'Bord edge banding — 50m rolls ~$67–$122 depending on species, so ~$1.50–$2.50/m. American Walnut cheapest (~$1.35/m); Blackbutt / Spotted Gum highest (~$2.20–$2.50/m). Using $2/m mid-point. Source: bord.com.au/collections/edge-banding',
    projects: [] },
];

BNE_2026.forEach(m => {
  m.libraryIds = ['lib-bne-2026'];
  MATERIALS.push(m);
});

// Map kind → library. Any material whose kind falls here gets assigned.
const KIND_TO_LIBRARY = {
  material:      'lib-finishes',
  appliance:     'lib-appliances',
  fitting:       'lib-fittings',
  light:         'lib-lighting',
  joinery:       'lib-joinery',
  'ffe-seating': 'lib-ffe',
  'ffe-tables':  'lib-ffe',
  'ffe-storage': 'lib-ffe',
  'ffe-beds':    'lib-ffe',
  'ffe-soft':    'lib-ffe',
  'ffe-lighting':'lib-ffe',
  'ffe-art':     'lib-ffe',
};

// Auto-assign seeded materials to a library based on their kind.
// Anything without a kind falls back to Finishes (legacy seeds).
MATERIALS.forEach(m => {
  if (m.libraryIds && m.libraryIds.length) return;
  const kind = m.kind || 'material';
  const lib = KIND_TO_LIBRARY[kind] || 'lib-finishes';
  m.libraryIds = [lib];
});
// Projects default: no library binding (= all libraries)
PROJECTS.forEach(p => { if (!p.libraryIds) p.libraryIds = []; });

window.MATERIALS = MATERIALS;
window.PROJECTS = PROJECTS;
window.CATEGORIES = CATEGORIES;
window.LIBRARIES = LIBRARIES;
window.KIND_TO_LIBRARY = KIND_TO_LIBRARY;
window.PAINT_BRANDS = PAINT_BRANDS;
window.PAINT_SHEENS = PAINT_SHEENS;
